becklyn_translations.dump:
    path: /dump/{locale}
    controller: 'Becklyn\Translations\Controller\DumpTranslationsController::dump'
    methods: [GET]
    requirements:
        locale: '[a-z]+([-_][a-zA-Z]+)?'
