services:
    _defaults:
        autoconfigure: true
        autowire: true
        bind:
            $projectDir: '%kernel.project_dir%'

    Becklyn\Translations\:
        resource: '../../*'
        exclude: '../../{Resources,BecklynTranslationsBundle.php}'
