services:
    _defaults:
        autoconfigure: true
        autowire: true
        bind:
            $projectDir: '%kernel.project_dir%'
            $cacheDir: '%kernel.cache_dir%'
            $isDebug: '%kernel.debug%'

    Becklyn\Translations\:
        resource: '../../*'
        exclude: '../../{Resources,BecklynTranslationsBundle.php}'

    Becklyn\Translations\Extractor\TranslationsExtractor:
        calls:
            - method: setConfigCacheFactory
              arguments:
                  - '@config_cache_factory'
