services:
    _defaults:
        autoconfigure: true
        autowire: true

    Becklyn\Translations\:
        resource: '../../*'
        exclude: '../../{Resources,BecklynTranslationsBundle.php}'

    Becklyn\Translations\Extractor\TranslationsCompiler:
        $projectDir: '%kernel.project_dir%'
